services:

  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 15s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.local
      secrets:
        - github_token
    volumes:
      - "./backend:/app"
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

  frontend:
    build:
       context: ./frontend
       dockerfile: Dockerfile.local
    volumes:
      - "./frontend:/frontend"
      - "/frontend/node_modules"
    ports:
      - "3001:3001"
    env_file:
      - .env
    command: npm run dev -- --host

  landing:
    build:
       context: ./landing
       dockerfile: Dockerfile.local
    volumes:
      - "./landing:/landing"
      - "/landing/node_modules"
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: npm run dev -- --host

volumes:
  postgres_data:

secrets:
  github_token:
    environment: GITHUB_TOKEN
