[project]
name = "daseen"
version = "0.1.0"
description = "Daseen"
readme = "README.md"
authors = [
    { name = "Kai Buschulte", email = "kb@beebucket.de" }
]
requires-python = ">=3.12"
dependencies = [
    "django>=5.0.6",
    "django-cors-headers>=4.3.1",
    "django-rest-framework>=0.1.0",
    "djangorestframework-simplejwt>=5.3.1",
    "drf-nested-routers>=0.94.1",
    "drf-yasg>=1.21.8",
    "gunicorn>=23.0.0",
    "psycopg>=3.2.4",
    "pymemcache>=4.0.0",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
extend-select = [
    "I", # isort replacement
    "S", # bandit
]

[dependency-groups]
dev = [
    "pytest-django>=4.9.0",
    "ruff>=0.9.3",
]

[tool.ruff.lint.per-file-ignores]
"backend/**/tests.py" = ["S101"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "daseen.settings"
# -- recommended but optional:
python_files = ["backend/**/tests.py"]
