FROM python:3.11

WORKDIR /backend

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY . .

CMD ["sh", "-c", "python manage.py collectstatic --noinput && python manage.py makemigrations apps.monitoring && python manage.py migrate && exec gunicorn --bind 0.0.0.0:8000 --workers 3 daseen.wsgi:application --timeout 120"]