# Generated by Django 5.0.6 on 2025-01-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('requested_url', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'success'), ('FAIL', 'fail')], default='SUCCESS', max_length=50)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
