# Generated by Django 5.1.6 on 2025-03-20 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_eventlog_type'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='dataspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.dataspace'),
        ),
    ]
