# Generated by Django 5.1.6 on 2025-03-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='dataspace',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dataspaces',
            field=models.ManyToManyField(blank=True, to='user.dataspace'),
        ),
    ]
