name: Docker Compose Build

on:
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-24.04
    name: Build Docker Images (no push)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create dummy .env file
        run: touch .env

      - name: Build with docker buildx bake
        uses: docker/bake-action@v6
        with:
          source: .
          files: production.yml
          push: false
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_HUB_API_KEY }}
