name: Playwright Tests

on:
  pull_request:
    branches:
      - main
      - dev
      - staging

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      REACT_APP_ELASTIC_URL: https://dl68t7d71bx5l.cloudfront.net/edp-data
      REACT_APP_IMAGE_BASE_PATH: https://d2xfg3kfb5x390.cloudfront.net/
      REACT_APP_LANDING_URL: http://localhost:3000
      REACT_APP_MAIN_URL: http://localhost:3001

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./frontend

      - name: Start Local Dev Server
        run: npm run dev &
        working-directory: ./frontend

      - name: Wait for Local Dev Server
        run: npx wait-on http://localhost:3001
        working-directory: ./frontend

      - name: Run Playwright Tests
        run: npx playwright test
        working-directory: ./frontend
