name: Playwright Tests

on:
  pull_request:
    branches:
      - main
      - dev
      - staging

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      VITE_ELASTIC_URL: http://localhost:8000/search
      VITE_IMAGE_BASE_PATH: https://d1q3gdh9qqr3rb.cloudfront.net/
      VITE_LANDING_URL: http://localhost:3000
      VITE_MAIN_URL: http://localhost:3001
      VITE_API_URL: http://localhost:8000

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./frontend

      - name: Set up Docker
        run: |
          docker compose -f local.yml up -d
        working-directory: .

      - name: Wait for services to be ready
        run: npx wait-on http://localhost:3001
        working-directory: ./frontend

      - name: Run Playwright Tests
        run: npx playwright test
        working-directory: ./frontend

      - name: Shutdown Docker containers
        run: docker compose -f local.yml down
        working-directory: .
