name: Playwright Tests

on:
  pull_request:
    branches:
      - main
      - dev
      - staging

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      REACT_APP_MAIN_URL: http://localhost:3001

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build React App
        run: CI=false npm run build
        working-directory: ./frontend

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./frontend

      - name: Start Local Server
        run: npx serve -s build -l 3001 &
        working-directory: ./frontend

      - name: Wait for Local Server
        run: npx wait-on http://localhost:3001
        working-directory: ./frontend

      - name: Run Playwright tests
        run: npx playwright test
        working-directory: ./frontend
