name: Playwright Tests

on:
  pull_request:
    branches:
      - main
      - dev
      - staging

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      VITE_ELASTIC_URL: https://api.daseen-staging.de/search
      VITE_IMAGE_BASE_PATH: https://d1q3gdh9qqr3rb.cloudfront.net/
      VITE_LANDING_URL: http://localhost:3000
      VITE_MAIN_URL: http://localhost:3001
      VITE_API_URL: https://api.daseen-staging.de/search

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./frontend

      - name: Run The Frontend
        run: |
          nohup npm run dev -- --host > dev.log 2>&1 &
        working-directory: ./frontend

      - name: Wait for services to be ready
        run: npx wait-on http://localhost:3001
        working-directory: ./frontend

      - name: Run Playwright Tests
        run: npx playwright test
        working-directory: ./frontend
