name: Release

on:
  push:
    tags: "*"
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_release_daseen:
    runs-on: ubuntu-24.04
    name: Build and Push daseen container
    timeout-minutes: 60
    env:
      DOCKER_REGISTRY: docker.io
    steps:
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          registry: ${{ env.DOCKER_REGISTRY }}
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Create dummy .env file
        run: touch .env

      - name: Build and push with Docker Bake
        uses: docker/bake-action@v6
        with:
          source: .
          files: production.yml
          push: true
          set: |
            backend.tags=${{ env.DOCKER_REGISTRY }}/beebucket/daseen-backend:${{ github.ref_name }}
            frontend.tags=${{ env.DOCKER_REGISTRY }}/beebucket/daseen-frontend:${{ github.ref_name }}
            landing.tags=${{ env.DOCKER_REGISTRY }}/beebucket/daseen-landing:${{ github.ref_name }}
            frontend.cache-from=type=gha,scope=frontend
            frontend.cache-to=type=gha,mode=max,scope=frontend
            landing.cache-from=type=gha,scope=landing
            landing.cache-to=type=gha,mode=max,scope=landing
            backend.cache-from=type=gha,scope=backend
            backend.cache-to=type=gha,mode=max,scope=backend
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_HUB_API_KEY }}
