name: Release

on:
    push:
        tags: "*"

jobs:
    build_and_release_daseen:
        runs-on: ubuntu-24.04
        name: Build and Push daseen react container
        timeout-minutes: 300
        env:
            DASEEN_SERACH_ENDPOINT: https://87ee3c2479304dcf8d716a1091e455bc.eu-central-1.aws.cloud.es.io/edp-data
            REGISTRY: docker.io
            IMAGE_PATH: beebucket/daseen
        steps:
        -   uses: docker/login-action@v3.1.0
            with:
                registry: ${{ env.REGISTRY }}
                username: cicdcorebeebucket
                password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        -   uses: actions/checkout@v4.1.4
            with:
                repository: ${{ github.repository }}
                token: ${{ secrets.GIT_HUB_API_KEY }}
                lfs: true
                submodules: recursive
        -   uses: docker/setup-qemu-action@v3.0.0
        -   uses: docker/setup-buildx-action@v3.3.0
        -   name: Extract Docker metadata
            id: meta
            uses: docker/metadata-action@v5.5.1
            with:
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_PATH }}
                flavor: latest=false
                tags: |
                    type=ref,event=branch
                    type=ref,event=tag
                    type=ref,event=pr
                    type=semver,pattern={{version}}
        -   name: Build and push Docker image
            id: build-and-push
            uses: docker/build-push-action@v5.3.0
            with:
                secrets: |
                    REPO_TOKEN=${{ secrets.GIT_HUB_API_KEY }}
                context: .
                file: frontend/Dockerfile.prod
                push: True
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                cache-from: type=gha
                cache-to: type=gha,mode=max
