name: Staging Deployment

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  build_and_push_staging:
    runs-on: ubuntu-24.04
    name: Build and Push Staging Containers
    steps:
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Create dummy .env file
        run: touch .env

      - name: Build and push with Docker Bake
        uses: docker/bake-action@v6
        with:
          source: .
          files: production.yml
          push: true
          set: |
            backend.tags=docker.io/beebucket/daseen-backend:staging
            frontend.tags=docker.io/beebucket/daseen-frontend:staging
            landing.tags=docker.io/beebucket/daseen-landing:staging
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_HUB_API_KEY }}

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.STAGING_SERVER_HOST }}
          username: ${{ secrets.STAGING_SERVER_USERNAME }}
          key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
          script: |
            cd ~/daseen-deploy
            ./deploy.sh
