name: Staging Deployment

on:
  push:
    branches:
      - staging

jobs:
  build_and_push_staging:
    runs-on: ubuntu-24.04
    name: Build and Push Staging Containers
    timeout-minutes: 300
    env:
      REGISTRY: docker.io
      IMAGE_PATH: beebucket/daseen
    steps:
    -   name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
            registry: ${{ env.REGISTRY }}
            username: cicdcorebeebucket
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    -   name: Check out repository
        uses: actions/checkout@v4

    -   name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

    -   name: Build and Push Services
        run: |
            # Build all services
            docker compose -f production.yml build

            # Automatically tag & push the services
            for service in $(docker compose -f production.yml config --services); do
                IMAGE_NAME="${{ env.IMAGE_PATH }}-$service:staging"
                docker tag $service $IMAGE_NAME
                docker push $IMAGE_NAME
            done

    -   name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
            host: ${{ secrets.STAGING_SERVER_HOST }}
            username: ${{ secrets.STAGING_SERVER_USERNAME }}
            key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
            script: |
                cd /daseen-deploy
                ./deploy.sh
